version: "3"

services:
  app:
    build: ./docker/php
    container_name: laravel_docker_app
    volumes:
      - ./src:/work
  web:
    image: nginx:1.19
    container_name: laravel_docker_web
    ports:
      - 20080:80
    volumes:
      - ./src:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./docker/db
    container_name: laravel_docker_db
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=laravel_docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 23306:3306
    security_opt:
      - seccomp:unconfined
